-- 코드를 입력하세요
SELECT USER_ID, NICKNAME, CONCAT(CITY,' ',STREET_ADDRESS1,' ',STREET_ADDRESS2) as 전체주소, CONCAT(left(TLNO,3),'-',mid(TLNO,4,4),'-',right(TLNO,4))전화번호
FROM USED_GOODS_BOARD as b, USED_GOODS_USER as u
WHERE b.WRITER_ID = u.USER_ID
GROUP BY 1
HAVING COUNT(USER_ID) >=3
ORDER BY 1 desc